#!/bin/bash

faketty () {
  script -qfec "$(printf "%q " "$@")" /dev/stdout
}

export $(dbus-launch)

faketty /sbin/agetty -o '-p -f -- \\u' --noclear --autologin ${USER} %I $TERM
# faketty /usr/bin/login -f ${LOGINUSER}
