FROM docker.io/archlinux:base

RUN set -exu \
  && pacman --noconfirm -Syyu \
  && pacman --noconfirm -Syy \
    gdm \
    gnome-shell \
    mesa \
    net-tools \
    pulseaudio \
    pulseaudio-alsa \
    socat \
    sudo \
    systemd \
    wayland \
    xorg-xwayland

COPY rootfs.base /

RUN set -exu \
  && dbus-uuidgen --ensure=/etc/machine-id \
  && dbus-uuidgen --ensure

VOLUME ["/sys/fs/cgroup"]
ENTRYPOINT ["/usr/local/sbin/init"]
