FROM docker.io/archlinux:base

RUN set -exu \
  && pacman --noconfirm -Syyu \
  && pacman --noconfirm -Syy \
    dbus \
    gnome-shell \
    wayland \
    xorg-xwayland \
    mesa \
    sudo \
    supervisor \
    socat

COPY rootfs.base /

CMD ["/bin/bash", "/entrypoint.sh"]
