FROM ghcr.io/kubevda/vdimage-arch-gnome-base:latest

RUN set -exu \
  && pacman --noconfirm -Syu \
  && pacman --noconfirm -Sy \
    code \
    curl \
    firefox \
    git \
    gnome \
    gnome-extra \
    gnome-shell-extensions \
    nano \
    wget

COPY rootfs.thin /
